### ISSUE TITLE
How to compile dtGUI?

### ISSUE THREAD

**Issue by jamesjinlv** [delta3d/delta3d#2]
When I compile the dtGUI module, I meet many errors;
Who can tell me how to compile?

**Comment by LEgregius** [comment]
The code works with CEGUI 0.7.9. It was never ported to 0.8

**Comment by jamesjinlv** [comment]
I know the code  works with CEGUI 0.7.9.
But I compile the code, there are lots of error,such as "dtGUI::CEGUIRenderer Cannot instantiate abstract class" and so on.
I know the reason, But the errors are too more, Could you tell why, How to quick complie?
thank you, LEgregius!

**Comment by LEgregius** [comment]
can you send me the full compiler output?

**Comment by jamesjinlv** [comment]
I send the full compiler output to you through email.
Thank you!

**Comment by jamesjinlv** [comment]
1 > ------- build started: Project: dtgui, configuration: release x64------

1> ceguirenderer.cpp

1 > D: \ JXM \ testdelta3d \ Inc \ dtgui / ceguiirender. H (57): error c2555: "dtgui:: ceguirenderer:: createtext": the return type of overriding virtual function is different, and it is not covariant from "CEGUI:: renderer:: createtext"

1 > D: \ JXM \ wwopenig \ wwopenigext \ include \ CEGUI / ceguirenderer. H (186): Note: see the declaration of "CEGUI:: renderer:: createtext"

1 > D: \ JXM \ testdelta3d \ Inc \ dtgui / ceguiirender. H (55): error c2555: "dtgui:: ceguirenderer:: createtext": the return type of overriding virtual function is different, and it is not covariant from "CEGUI:: renderer:: createtext"

1 > D: \ JXM \ wwopenig \ wwopenigext \ include \ CEGUI / ceguirenderer. H (162): Note: see the declaration of "CEGUI:: renderer:: createtext"

1 >.. \ SRC \ dtgui \ ceguirder.cpp (297): error c2259: "dtgui:: ceguitexture": abstract class cannot be instantiated

1 >.. \ SRC \ dtgui \ ceguirder.cpp (297): Note: due to the following members:

1 >.. \ SRC \ dtgui \ ceguirder.cpp (297): Note: "const CEGUI:: size & CEGUI:: texture:: getSize (void) const": Abstract

1 > D: \ JXM \ wwopenig \ wwopenigext \ include \ CEGUI / ceguitexture. H (74): Note: see the declaration of "CEGUI:: texture:: getSize"

1 >.. \ SRC \ dtgui \ ceguirder.cpp (297): Note: "const CEGUI:: size & CEGUI:: texture:: getoriginaldatasize (void) const": Abstract

1 > D: \ JXM \ wwopenig \ wwopenigext \ include \ CEGUI / ceguitexture. H (84): Note: see the declaration of "CEGUI:: texture:: getoriginaldatasize"

1 >.. \ SRC \ dtgui \ ceguirder.cpp (580): error c2065: "eventdisplaysizechanged": undeclared identifier

1 >.. \ SRC \ dtgui \ ceguirder.cpp (580): error c2065: "eventnamespace": undeclared identifier

1 >.. \ SRC \ dtgui \ ceguirder.cpp (580): error c3861: "fireevent": identifier not found

1 >.. \ SRC \ dtgui \ ceguirder.cpp (587): error c2065: "d" identifierstring ": undeclared identifier

1 > D: \ JXM \ testdelta3d \ Inc \ dtgui / ceguiirender. H (57): error c2555: "dtgui:: ceguirenderer:: createtext": the return type of overriding virtual function is different, and it is not covariant from "CEGUI:: renderer:: createtext"

1 > D: \ JXM \ wwopenig \ wwopenigext \ include \ CEGUI / ceguirenderer. H (186): Note: see the declaration of "CEGUI:: renderer:: createtext"

1 > D: \ JXM \ testdelta3d \ Inc \ dtgui / ceguiirender. H (55): error c2555: "dtgui:: ceguirenderer:: createtext": the return type of overriding virtual function is different, and it is not covariant from "CEGUI:: renderer:: createtext"

1 > D: \ JXM \ wwopenig \ wwopenigext \ include \ CEGUI / ceguirenderer. H (162): Note: see the declaration of "CEGUI:: renderer:: createtext"

1 >.. \ SRC \ dtgui \ ceguitexture.cpp (19): error C2664: "CEGUI:: texture:: texture (const CEGUI:: texture &)": cannot convert parameter 1 from "CEGUI:: renderer *" to "const CEGUI:: texture &"

1 >.. \ SRC \ dtgui \ ceguitexture.cpp (19): Note: cannot convert from "CEGUI:: renderer *" to "const CEGUI:: texture"

1 >.. \ SRC \ dtgui \ ceguitexture.cpp (19): Note: no constructor can accept the source type, or the constructor overload decision is ambiguous

1 >.. \ SRC \ dtgui \ ceguitexture.cpp (35): error c3861: "getrenderer": identifier not found

1 > D: \ JXM \ testdelta3d \ Inc \ dtgui / ceguiirender. H (57): error c2555: "dtgui:: ceguirenderer:: createtext": the return type of overriding virtual function is different, and it is not covariant from "CEGUI:: renderer:: createtext"

1 > D: \ JXM \ wwopenig \ wwopenigext \ include \ CEGUI \ ceguirenderer. H (186): Note: see the declaration of "CEGUI:: renderer:: createtext"

1 > D: \ JXM \ testdelta3d \ Inc \ dtgui / ceguiirender. H (55): error c2555: "dtgui:: ceguirenderer:: createtext": the return type of overriding virtual function is different, and it is not covariant from "CEGUI:: renderer:: createtext"

1 > D: \ JXM \ wwopenig \ wwopenigext \ include \ CEGUI \ ceguirenderer. H (162): Note: see the declaration of "CEGUI:: renderer:: createtext"

1 > D: \ JXM \ testdelta3d \ Inc \ dtgui / render. H (27): fatal error C1083: cannot open include file: "CEGUI / rendermodules / openglguirenderer / openglrender. H": no such file or directory

1 > D: \ JXM \ testdelta3d \ Inc \ dtgui / ceguiirender. H (55): error c2555: "dtgui:: ceguirenderer:: createtext": the return type of overriding virtual function is different, and it is not covariant from "CEGUI:: renderer:: createtext"

1 > D: \ JXM \ wwopenig \ wwopenigext \ include \ CEGUI \ ceguirenderer. H (162): Note: see the declaration of "CEGUI:: renderer:: createtext"

1 >.. \ SRC \ dtgui \ hud.cpp (63): error C2664: "dtgui:: ceguimouselistener:: ceguimouselistener (const dtgui:: ceguimouselistener &)": cannot convert parameter 1 from "dtgui:: HUD * const" to "const dtgui:: ceguimouselistener &"

1 >.. \ SRC \ dtgui \ hud.cpp (63): Note: the reason is as follows: cannot convert from "dtgui:: HUD * const" to "const dtgui:: ceguimouselistener"

1 >.. \ SRC \ dtgui \ hud.cpp (63): Note: no constructor can accept the source type, or the constructor overload decision is ambiguous

1 >.. \ SRC \ dtgui \ hud.cpp (64): error C2664: "dtgui:: ceguikeyboardlistener:: ceguikeyboardlistener (const dtgui:: ceguikeyboardlistener &)": cannot convert parameter 1 from "dtgui:: HUD * const" to "const dtgui:: ceguikeyboardlistener &"

1 >.. \ SRC \ dtgui \ hud.cpp (64): Note: the reason is as follows: cannot convert from "dtgui:: HUD * const" to "const dtgui:: ceguikeyboardlistener"

1 >.. \ SRC \ dtgui \ hud.cpp (64): Note: no constructor can accept the source type, or the constructor overload decision is ambiguous

1 >.. \ SRC \ dtgui \ hud.cpp (66): error c2653: "action": not a class or namespace name

1 >.. \ SRC \ dtgui \ hud.cpp (66): error c2276: "&": illegal operation on binding member function expression

1 >.. \ SRC \ dtgui \ hud.cpp (66): error c2672: "sigslot:: signal3 < const dtutil:: refstring &, double, double, sigslot:: multi-threaded_local >:: connect_slot": no matching overloaded function found

1 >.. \ SRC \ dtgui \ hud.cpp (144): error c2039: "getprefix": not a member of "CEGUI:: window"

1 > D: \ JXM \ wwopenig \ wwopenigext \ include \ CEGUI \ ceguiwindow. H (138): Note: see the declaration of "CEGUI:: window"

1 >.. \ SRC \ dtgui \ hud.cpp (144): error c2228: "the left side of". C_str "must have class / structure / Union

1 >.. \ SRC \ dtgui \ hud.cpp (167): error c2660: "CEGUI:: WindowManager:: CreateWindow": the function does not accept three parameters

1 >.. \ SRC \ dtgui \ hud.cpp (237): error c2660: "CEGUI:: WindowManager:: CreateWindow": the function does not accept three parameters

1 >.. \ SRC \ dtgui \ hud.cpp (282): error c2259: "dtgui:: ceguirenderer": abstract class cannot be instantiated

1 >.. \ SRC \ dtgui \ hud.cpp (447): error c2039: "createimageset": not a member of "CEGUI:: imagesetmanager"

1 > D: \ JXM \ wwopenig \ wwopenigext \ include \ CEGUI \ ceguiimagesetmanager. H (56): Note: see the declaration of "CEGUI:: imagesetmanager"

1 >.. \ SRC \ dtgui \ hud.cpp (457): error c2039: "destroyimageset": not a member of "CEGUI:: imagesetmanager"

1 > D: \ JXM \ wwopenig \ wwopenigext \ include \ CEGUI \ ceguiimagesetmanager. H (56): Note: see the declaration of "CEGUI:: imagesetmanager"

1 >.. \ SRC \ dtgui \ hud.cpp (458): error C2664: "void CEGUI:: renderer:: destroytexture (CEGUI:: texture &)": cannot convert parameter 1 from "dtgui:: ceguitexture *" to "CEGUI:: texture &"

1 >.. \ SRC \ dtgui \ hud.cpp (485): error c2039: "createimageset": not a member of "CEGUI:: imagesetmanager"

1 > D: \ JXM \ wwopenig \ wwopenigext \ include \ CEGUI \ ceguiimagesetmanager. H (56): Note: see the declaration of "CEGUI:: imagesetmanager"

1 >.. \ SRC \ dtgui \ hud.cpp (492): error c2039: "createimagesetfromimagefile": not a member of "CEGUI:: imagesetmanager"

1 > D: \ JXM \ wwopenig \ wwopenigext \ include \ CEGUI \ ceguiimagesetmanager. H (56): Note: see the declaration of "CEGUI:: imagesetmanager"

1 >.. \ SRC \ dtgui \ hud.cpp (499): error c2039: "destroyimageset": not a member of "CEGUI:: imagesetmanager"

1 > D: \ JXM \ wwopenig \ wwopenigext \ include \ CEGUI \ ceguiimagesetmanager. H (56): Note: see the declaration of "CEGUI:: imagesetmanager"

1 >.. \ SRC \ dtgui \ hud.cpp (506): error c2039: "destroyallimagesets": not a member of "CEGUI:: imagesetmanager"

1 > D: \ JXM \ wwopenig \ wwopenigext \ include \ CEGUI \ ceguiimagesetmanager. H (56): Note: see the declaration of "CEGUI:: imagesetmanager"

1 >.. \ SRC \ dtgui \ hud.cpp (513): error c2039: "loadscheme": not a member of "CEGUI:: schememanager"

1 > D: \ JXM \ wwopenig \ wwopenigext \ include \ CEGUI \ ceguischememanager. H (52): Note: see the declaration of "CEGUI:: schememanager"

1 >.. \ SRC \ dtgui \ hud.cpp (520): error c2039: "unloadscheme": not a member of "CEGUI:: schememanager"

1 > D: \ JXM \ wwopenig \ wwopenigext \ include \ CEGUI \ ceguischememanager. H (52): Note: see the declaration of "CEGUI:: schememanager"

1 >.. \ SRC \ dtgui \ hud.cpp (527): error c2039: "unloadallschemes": not a member of "CEGUI:: schememanager"

1 > D: \ JXM \ wwopenig \ wwopenigext \ include \ CEGUI \ ceguischememanager. H (52): Note: see the declaration of "CEGUI:: schememanager"

1 >.. \ SRC \ dtgui \ hud.cpp (534): error c2039: "createfont": not a member of "CEGUI:: fontmanager"

1 > D: \ JXM \ wwopenig \ wwopenigext \ include \ CEGUI \ ceguifontmanager. H (58): Note: see the declaration of "CEGUI:: fontmanager"

1 >.. \ SRC \ dtgui \ hud.cpp (541): error c2039: "destroyfont": not a member of "CEGUI:: fontmanager"

1 > D: \ JXM \ wwopenig \ wwopenigext \ include \ CEGUI \ ceguifontmanager. H (58): Note: see the declaration of "CEGUI:: fontmanager"

1 >.. \ SRC \ dtgui \ hud.cpp (548): error c2039: "destroyallfonts": not a member of "CEGUI:: fontmanager"

1 > D: \ JXM \ wwopenig \ wwopenigext \ include \ CEGUI \ ceguifontmanager. H (58): Note: see the declaration of "CEGUI:: fontmanager"

1 >.. \ SRC \ dtgui \ hud.cpp (562): error c2039: "isimagesetpresent": not a member of "CEGUI:: imagesetmanager"

1 > D: \ JXM \ wwopenig \ wwopenigext \ include \ CEGUI \ ceguiimagesetmanager. H (56): Note: see the declaration of "CEGUI:: imagesetmanager"

1 >.. \ SRC \ dtgui \ hud.cpp (569): error c2039: "ischemepresent": not a member of "CEGUI:: schememanager"

1 > D: \ JXM \ wwopenig \ wwopenigext \ include \ CEGUI \ ceguischememanager. H (52): Note: see the declaration of "CEGUI:: schememanager"

1> renderer.cpp

1 > D: \ JXM \ testdelta3d \ Inc \ dtgui / render. H (27): fatal error C1083: cannot open include file: "CEGUI / rendermodules / openglguirenderer / openglrender. H": no such file or directory

==========Build: 0 succeeded, 1 failed, 0 latest, 0 skipped==========

**Comment by jamesjinlv** [comment]
LEgregius, Could you help me?

**Comment by LEgregius** [comment]
Hi,
I haven't been able to reproduce this error.   What are the contents of your CEGUIVersion.h header?

**Comment by LEgregius** [comment]
Also, what is your environment like? Compiler versions, etc.

**Comment by LEgregius** [comment]
Actually, I just noticed that you're missing files.  D: \ JXM \ testdelta3d \ Inc \ dtgui / render. H (27): fatal error C1083: cannot open include file: "CEGUI / rendermodules / openglguirenderer / openglrender. H": no such file or directory. You don't have the opengl renderer headers available.

**Comment by jamesjinlv** [comment]
the contents of your CEGUIVersion.h header is following;
#ifndef _CEGUIVersion_h_
#define _CEGUIVersion_h_

//////////////////////////////////////////////////////////////////////////
// Define CEGUI version
//////////////////////////////////////////////////////////////////////////
#define CEGUI_VERSION_MAJOR 0
#define CEGUI_VERSION_MINOR 7
#define CEGUI_VERSION_PATCH 9

**Comment by jamesjinlv** [comment]
The subdirectory of cegui-CEGUI-0.7.9-r5\cegui\include\RendererModules are
Direct3D9
Direct3D10
Direct3D11
DirectFB
Irrlicht
Null
Ogre
Opengl
there is no the openglguirenderer subdirectory.
Do you have openglguirenderer subdirectory.

**Comment by LEgregius** [comment]
Your error is "CEGUI / rendermodules / openglguirenderer / openglrender. H", 

but the code actually includes:  

#include <CEGUI/RendererModules/OpenGLGUIRenderer/openglrenderer.h>

Why are they different? I'm building on macOS.  

I don't know recall if there would be a reason why you would have different subdirectories. Is there the openglrenderer.h ultimately inside the Opengl directory? Did build your own dependencies, or where did you get them? It used to work on windows, so I'm trying to figure out what could changed.

**Comment by jamesjinlv** [comment]
This error is not the key problem, because I know to deal with "cegui-CEGUI-0.7.9-r5\cegui\include\RendererModules\OpenGL\CEGUIOpenGLRenderer.h" replace.
The other errors?
I wonder Why so much errors to compile dtGUI with CEGUI 0.7.9?

**Comment by LEgregius** [comment]
Once the file is found, what errors do you get? I was guessing that the errors were at least partly because the of missing file.

What version of source do you have? The master on github?

**Comment by jamesjinlv** [comment]
some of errors are following;

1 >.. \ SRC \ dtgui \ ceguirder.cpp (297): error c2259: "dtgui:: ceguitexture": abstract class cannot be instantiated
1 >.. \ SRC \ dtgui \ ceguirder.cpp (580): error c2065: "eventdisplaysizechanged": undeclared identifier
1 >.. \ SRC \ dtgui \ ceguirder.cpp (580): error c2065: "eventnamespace": undeclared identifier
1 >.. \ SRC \ dtgui \ ceguirder.cpp (580): error c3861: "fireevent": identifier not found

**Comment by jamesjinlv** [comment]
Who can help

some of errors are following;

1 >.. \ SRC \ dtgui \ ceguirder.cpp (297): error c2259: "dtgui:: ceguitexture": abstract class cannot be instantiated
1 >.. \ SRC \ dtgui \ ceguirder.cpp (580): error c2065: "eventdisplaysizechanged": undeclared identifier
1 >.. \ SRC \ dtgui \ ceguirder.cpp (580): error c2065: "eventnamespace": undeclared identifier
1 >.. \ SRC \ dtgui \ ceguirder.cpp (580): error c3861: "fireevent": identifier not found

**Comment by LEgregius** [comment]
Hi jamesjinlv,

What is ceguirder? It looks like it's related to ceguirenderer.cpp, but that file is only for running with very old versions of CEGUI.  The only files it should be building are ones listed in CMakeLists.txt

SET(LIB_SOURCES
   ${SOURCE_PATH}/ceguikeyboardlistener.cpp
   ${SOURCE_PATH}/ceguimouselistener.cpp
   ${SOURCE_PATH}/gui.cpp
   ${SOURCE_PATH}/resourceprovider.cpp
   ${SOURCE_PATH}/scriptmodule.cpp
)

how are you building this, because the cmake build doesn't reference that file anywhere.
